// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"database/sql"

	"github.com/google/uuid"
)

type Distributor struct {
	ID     uuid.UUID
	Name   string
	Member []uuid.UUID
	Owner  uuid.UUID
}

type Place struct {
	ID          uuid.UUID
	Distributor int64
	Username    string
	Name        string
	Title       string
	Description string
	Address     string
	Grade       sql.NullFloat64
	ReviewsNum  int32
	Tags        string
}
